server:
  port: 8888

spring:
  application:
    name: config-service
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file://${user.home}/dev/msa/git-local-repo
        git: # https://cloud.spring.io/spring-cloud-config/reference/html/
#                    uri: file:///Users/gary/dev/msa/git-local-repo
          uri: https://github.com/wooheet/spring-cloud-config
#          username: [username]
#          password: [password]

management:
  endpoints:
    web:
      exposure:
        include: health, busrefresh

